name: Code Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
  
    - run: flutter clean
    - run: flutter pub get
    - run: flutter pub run intl_utils:generate
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: dart format ./lib --set-exit-if-changed
    - run: flutter analyze
